# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and deploy it to AWS S3
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Upload Distribution Package
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: ./dist
          if-no-files-found: error
  deploy:
    needs: build
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download Distribution Package
        uses: actions/download-artifact@v4
        with:
          name: distribution
          path: dist
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Copy dist folder to s3
        run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }}/
